### ISSUE TITLE
openssl 1.1.1g does not compile correctly on CentOS 7.8

### ISSUE THREAD

**Issue by runlevel5** [Homebrew/linuxbrew-core#20267]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

openssl 1.1.1g does not compile correctly on CentOS 7.8. The issue is exactly this one upstream. Please see link https://github.com/openssl/openssl/issues/9921

## What happened (include command output)

When the `make test` step kicks in, I got following error:

```
make[1]: Entering directory `/tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g'
make[1]: Leaving directory `/tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g'
make[1]: Entering directory `/tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=`cd .././engines 2>/dev/null && pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_comp )
../test/recipes/70-test_comp.t .. 
Can't locate Test/More.pm in @INC (@INC contains: /tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g/test/../util/perl /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1g/libexec/lib/perl5/ppc64le-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1g/libexec/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g/test/../util/perl/OpenSSL/Test.pm line 13.
BEGIN failed--compilation aborted at /tmp/openssl@1.1-20200501-4787-11vka3l/openssl-1.1.1g/test/../util/perl/OpenSSL/Test.pm line 13.
Compilation failed in require at ../test/recipes/70-test_comp.t line 10.
BEGIN failed--compilation aborted at ../test/recipes/70-test_comp.t line 10.
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

## What you expected to happen

No error :)

## Step-by-step reproduction instructions (by running `brew install` commands)

* Use Centos 7.8
* `HOMEBREW_DEBUG=1 brew install openssl`

**Comment by runlevel5** [comment]
The `Test::More` package is missing and could be installed as part of the formula like the `Test::Harness`

**Comment by iMichka** [comment]
Yes, that's how this can be fixed. Please open a pull request.
