### ISSUE TITLE
Rogue Formula is unable to build on ubuntu 20.04.2

### ISSUE THREAD

**Issue by rcoconnor** [Homebrew/linuxbrew-core#23241]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I typed "brew gist-logs rogue" into my terminal, the output can be found here: https://gist.github.com/rcoconnor/dcf9116a49c7fa9f49e2b0c48dfc77d9
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install rogue on my terminal so I could play the classic game. 

### What happened (include all command output)?

The following is what was outputted when trying to install rogue with homebrew, which shows that the formula is unable to build.

~ brew install rogue
==> Downloading https://src.fedoraproject.org/repo/pkgs/rogue/rogue5.4.4-src.tar.gz/033288f46444b06814c81ea69d96e075/rogue5.4.4-src.tar.gz
Already downloaded: /home/roryoconnor/.cache/Homebrew/downloads/a1af676b2521db01d688980dfee67e4d04ff7d92d07ed999fc2d1c209b775eb7--rogue5.4.4-src.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/rogue/5.4.4
==> make install
Last 15 lines from /home/roryoconnor/.cache/Homebrew/Logs/rogue/02.make:
armor.c:12:10: fatal error: curses.h: No such file or directory
   12 | #include <curses.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:130: armor.o] Error 1
chase.c:14:10: fatal error: curses.h: No such file or directory
   14 | #include <curses.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:130: chase.o] Error 1
command.c:15:10: fatal error: curses.h: No such file or directory
   15 | #include <curses.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:130: command.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

### What did you expect to happen?

I expected it to install the program as it usually does. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
install homebrew on ubuntu 20.04.2
run "brew install rogue"
```

**Comment by danielnachun** [comment]
I've opened a PR to fix this in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/77482.  Once it is merged upstream, it will be merged here and a bottle will be built.

**Comment by danielnachun** [comment]
That PR was merged and the formula is now bottled on Linux, so this is fixed!

**Comment by rcoconnor** [comment]
Glorious!
