### ISSUE TITLE
Link error after upgrading to python@3.8-3.8.2_1

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#20174]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run tox or thefuck.

## What happened (include command output)

I tried to run tox after upgrading and it seems that the symlinks are broken to both tox and thefuck.

<details>
  <summary>Command output</summary>
  <pre>
   tox
  /home/linuxbrew/.linuxbrew/Cellar/tox/3.14.6/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

  </pre>
</details>

## What you expected to happen

tox should work

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install tox
brew upgrade
tox

**Comment by mellery451** [comment]
same issue with pylint (and likely many other packages):
     09:18 $ pylint --version
/home/linuxbrew/.linuxbrew/Cellar/pylint/2.4.4_2/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

**Comment by iMichka** [comment]
I confirm that we have this issue.

```
brew linkage pylint
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Missing libraries:
  libpython3.8.so.1.0
```

/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/libpython3.8.so.1.0` exists ...

Rebuilding `pylint` from source fixes this:
```
brew linkage pylint
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.2_1/lib/libpython3.8.so.1.0 (python@3.8)
```

**Comment by iMichka** [comment]
pkg-config looks good:
```
cat /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.2_1/lib/pkgconfig/python-3.8.pc
# See: man pkg-config
prefix=/home/linuxbrew/.linuxbrew/opt/python@3.8
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Build a C extension for Python
Requires:
Version: 3.8
Libs.private: -lcrypt -lpthread -ldl  -lutil -lm
Libs:
Cflags: -I${includedir}/python3.8
```

The main issue is that these libraries are linked against the plain Cellar path, which might change on a revision bump. The linkage should be done against the `opt` path.

**Comment by thedrow** [comment]
I can confirm that building from source fixes the issue.

**Comment by Spedge** [comment]
(Apologies if this is the wrong place, first-time brew users trying to do the right thing)

Hey folks - I'm seeing the same issue (I think) with the awscli@2 formula. Freshly installed this morning (awscli 2.0.8)
```
$ ldd /home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.8/libexec/bin/python3.8
        linux-vdso.so.1 (0x00007fffd6319000)
        libpython3.8.so.1.0 => not found
        libpthread.so.0 => /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (0x00007f6d969e0000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/lib/libc.so.6 (0x00007f6d96641000)
        /home/linuxbrew/.linuxbrew/lib/ld.so (0x00007f6d96c00000)
```
This means when I run the aws command...
```
╰$ aws
/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.8/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```
When I set the the LD_LIBRARY_PATH variable manually, works fine.


```
╰$ LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.2_1/lib/ aws
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command

```

Not sure if this is the same problem. If it's not, let me know and I can re-raise somewhere more appropriate.

**Comment by thedrow** [comment]
I think it is the same.

Try reinstalling from source using `brew install -s <pkgname>`.

**Comment by iMichka** [comment]
Yes. All these errors are the same. The root cause is in the Python 3.8 formula; and we did not notice before because it's the first time we updated the revision for 3.8.

I found the error, and have made a fix: #20182
Once this is merged, we will need to rebuild all the packages linking against python@3.8, so that they link against the right path.

**Comment by iMichka** [comment]
I pushed a new python 3.8 bottle with a fix. We will rebuild all the broken bottles in #20188, you can follow the list there to see how it goes.

**Comment by Char-Aznable** [comment]
@iMichka I get the same error when running a `brew install python@3.8 --keep-tmp`. The relevant error is:
```
LD_LIBRARY_PATH=/tmp/python@3.8-20200421-26147-19hvkzx/Python-3.8.2 CC='gcc-5 -pthread' LDSHARED='gcc-5 -pthread -shared -L/home/aznb/.linuxbrew/lib   ' OPT='-DNDEBUG -g  -O3 -Wall'   _TCLTK_INCLUDES='' _TCLTK_LIBS=''  ./python -E ./setup.py  build
running build
running build_ext
ldd: /home/aznb/.linuxbrew/opt/readline/lib/libhistory.dylib: No such file or directory
sqlite: found /home/aznb/.linuxbrew/opt/sqlite/include/sqlite3.h
/home/aznb/.linuxbrew/opt/sqlite/include/sqlite3.h: version 3.31.1
building '_struct' extension
building 'array' extension
building '_contextvars' extension
building 'math' extension
building '_datetime' extension
........
/bin/sh: line 9: 35690 Illegal instruction     (core dumped) LD_LIBRARY_PATH=/tmp/python@3.8-20200421-26147-19hvkzx/Python-3.8.2 CC='gcc-5 -pthread' LDSHARED='gcc-5 -pthread -shared -L/home/aznb/.linuxbrew/lib   ' OPT='-DNDEBUG -g  -O3 -Wall' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
```
ldd the compiled "python" binary in the tmp dir:
```
        linux-vdso.so.1 (0x00007ffc4a364000)
        libpython3.8.so.1.0 => not found
        libcrypt.so.1 => /home/aznb/.linuxbrew/lib/libcrypt.so.1 (0x00002b9f4559e000)
        libpthread.so.0 => /home/aznb/.linuxbrew/lib/libpthread.so.0 (0x00002b9f455d6000)
        libdl.so.2 => /home/aznb/.linuxbrew/lib/libdl.so.2 (0x00002b9f455f6000)
        libutil.so.1 => /home/aznb/.linuxbrew/lib/libutil.so.1 (0x00002b9f455fb000)
        libm.so.6 => /home/aznb/.linuxbrew/lib/libm.so.6 (0x00002b9f45600000)
        libc.so.6 => /home/aznb/.linuxbrew/lib/libc.so.6 (0x00002b9f456ff000)
        /home/aznb/.linuxbrew/lib/ld.so (0x00002b9f45573000)
```

**Comment by Char-Aznable** [comment]
At least this line https://github.com/Homebrew/linuxbrew-core/blob/4e64ed977b8ff5e5c994cc9e115ebf84482f0e8f/Formula/python%403.8.rb#L132 shouldn't be used on linux

**Comment by iMichka** [comment]
Hi. Can you confirm that you are working with version 3.8.2_4 (revision 4). All the others are known to be broken.

To me it looks like your python 3.8 compilation failed with `/bin/sh: line 9: 35690 Illegal instruction     (core dumped)`, so I would not expect something working out of that anyway.

Regarding the dylib line, it has been there in python 3.7 since forever, and 3.8 since it is out, and has never caused any harm. But yes we could disable that for Linux.

I rebuilt 144 packages with the latest version of Python 3.8 and encountered no issue on our CI.

Could you post a full log?

**Comment by Char-Aznable** [comment]
Yes, it's revision 4. My brew --version is `Homebrew 2.2.13-122-g20f7f26
Homebrew/linuxbrew-core (git revision aee486; last commit 2020-04-21)`. 

I just found that the python formula version 3.7.7 revision 1 also has the `Illegal instruction (core dumped)` error on the same build command `./python -E ./setup.py build` in the tmp dir. But my last build of python 3.7.6_1 worked. Here are the log files:
[python@3.8.tar.gz](https://github.com/Homebrew/linuxbrew-core/files/4512756/python%403.8.tar.gz)

**Comment by andreineculau** [comment]
@iMichka Is this issue solved completely? I see that in the past days the same error message was solved for awscli, but it's still there for awslogs e.g. https://travis-ci.com/github/rokmoln/support-firecloud/jobs/343770221 

I see in https://github.com/Homebrew/linuxbrew-core/issues/20188 that some formulas have been addressed manually (like awscli), but then the automation that should have fixed the other formulae failed https://github.com/Homebrew/linuxbrew-core/pull/20192#issuecomment-617334444

Apologies if the above investigation is non-sense.

**Comment by iMichka** [comment]
I can confirm that there is still an issue. It might be slightly different. I'll investigate:
```
ldd /home/linuxbrew/.linuxbrew/Cellar/awslogs/0.11.0_4/libexec/bin/python
	linux-vdso.so.1 =>  (0x00007ffef6eaf000)
	libpython3.8.so.1.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9465997000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94655cd000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007f9465bb4000)
```

**Comment by iMichka** [comment]
```
patchelf --print-rpath $(brew --prefix awslogs)/libexec/bin/python
/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.2_4/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/xz/lib:/home/linuxbrew/.linuxbrew/opt/gdbm/lib:/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/opt/readline/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/sqlite/lib:/home/linuxbrew/.linuxbrew/opt/bzip2/lib:/home/linuxbrew/.linuxbrew/opt/libffi/lib
```

This should keep the paths fixed but is not working on linux:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L230-L241

```
root@a308d8e4e846:/home/linuxbrew/.linuxbrew/opt/awslogs/libexec/bin# file python3.8
python3.8: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, for GNU/Linux 2.6.32, BuildID[sha1]=fc5e55e2dbceb43200fa062731a5f70cf9c1112e, not stripped
```

**Comment by tsuyoshicho** [comment]
## memo:

update 2020/06/10
python@3.8 and docutils ver 0.16_2 same issue

```
brew linkage docutils
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Missing libraries:
  libpython3.8.so.1.0
```

temporary workaround: docutils 0.16_1 pinned and use it. (before migrate 3.8)

I am waiting for this issue to be resolved.

**Comment by iMichka** [comment]
A short term solution is to bump the revision of that formula; and build a new bottle. Can you open a pull request for that?

I still need to investigate what is broken in Python right now, but had no time to investigate.

**Comment by iMichka** [comment]
Looks like the changes in https://github.com/Homebrew/brew/commit/2594e7093e is the culprit. I am investigating this with @Bo98 .

**Comment by iMichka** [comment]
Actually this part of the code is working fine.

The difference in linkage for the python3.8 files in the docutils formula:
```
 otool -L /usr/local/Cellar/docutils/0.16_1/libexec/bin/python3.8
/usr/local/Cellar/docutils/0.16_1/libexec/bin/python3.8:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	@executable_path/../.Python (compatibility version 3.8.0, current version 3.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

```
ldd /home/linuxbrew/.linuxbrew/opt/docutils/libexec/bin/python3.8
	linux-vdso.so.1 =>  (0x00007ffd0995e000)
	libpython3.8.so.1.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa191dd4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa191a0a000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fa191ff1000)
```

In the python formula:
```
otool -L /usr/local/Cellar/python@3.8/3.8.3_1/bin/python3.8
/usr/local/Cellar/python@3.8/3.8.3_1/bin/python3.8:
	/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/Python (compatibility version 3.8.0, current version 3.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

```
ldd /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8
	linux-vdso.so.1 =>  (0x00007ffe9f9d1000)
	libpython3.8.so.1.0 => /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.3/lib/libpython3.8.so.1.0 (0x00007f03df5ee000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f03df3d1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f03df007000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f03dee03000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f03dec00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f03de8f7000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007f03dfb34000)
```

**Comment by Bo98** [comment]
What does `ldd` look like for a Python 3.7 formula?

**Comment by zhangpy** [comment]
when the version 3.8.2_4 will merge to master branch? my python@3.8 is 3.8.3 version.

**Comment by iMichka** [comment]
3.8.3 > 3.8.2_4

**Comment by zhangpy** [comment]
> 3.8.3 > 3.8.2_4
oh, installing from source fix my issue. thanks.
